version: '3.8'
services:
  auth-api:
    image: enganderson/auth-api
    container_name: auth-api
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env

networks:
  default:
    external: true
    name: orianderson
