version: '3.8'
services:
  auth-api:
    image: enganderson/server-auth
    container_name: auth-api
    restart: always
    ports:
      - 3000:3000
    env_file:
      - production.env

networks:
  default:
    external: true
    name: orianderson
